CREATE DATABASE DB_TIENDA
ON 
(NAME = 'DB_TIENDA_DATA',
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\DB_TIENDA_DATA.MDF')
LOG ON
(NAME='DB_TIENDA_LOG',
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\DB_TIENDA_LOG.LDF')
COLLATE SQL_Latin1_General_CP1_CI_AS
GO 

CREATE TABLE DB_TIENDA.dbo.CAT_COMPAÑIAS
(
	NID_COMPAÑIA INT IDENTITY (1,1) NOT NULL,
	CCOMPAÑIA VARCHAR (30) NOT NULL,
	BHABILITADO BIT NOT NULL,
	DFECHA_ALTA DATE NOT NULL,
	DFECHA_BAJA DATE NULL,
	CONSTRAINT PK_NID_COMPAÑIA PRIMARY KEY (NID_COMPAÑIA)
)
GO

CREATE TABLE DB_TIENDA.dbo.TBL_MARCAS
(
	NID_MARCA INT IDENTITY (1,1) NOT NULL,
	CMARCA VARCHAR (30) NOT NULL,
	NID_COMPAÑIA INT NOT NULL,
	BHABILITADO BIT NOT NULL,
	DFECHA_ALTA DATE NOT NULL,
	DFECHA_BAJA DATE NULL,
	CONSTRAINT PK_NID_MARCA PRIMARY KEY (NID_MARCA),
	CONSTRAINT FK_NID_COMPAÑIA FOREIGN KEY (NID_COMPAÑIA) REFERENCES dbo.CAT_COMPAÑIAS (NID_COMPAÑIA)
)
GO

CREATE TABLE DB_TIENDA.dbo.CAT_CLIENTES
(
	NID_CLIENTE INT IDENTITY (1,1) NOT NULL,
	CNOMBRES VARCHAR (40) NOT NULL,
	CAPELLIDO_PATERNO VARCHAR (20) NOT NULL,
	CAPELLIDO_MATERNO VARCHAR (20) NULL,
	CTELEFONO CHAR(10) NOT NULL,
	CEMAIL VARCHAR(35) NULL,
	BHABILITADO BIT NOT NULL,
	DFECHA_ALTA DATE NOT NULL,
	DFECHA_BAJA DATE NULL,
	CONSTRAINT PK_NID_CLIENTE PRIMARY KEY (NID_CLIENTE)

)
GO

CREATE TABLE DB_TIENDA.dbo.CAT_TIPO_PRODUCTOS
(
	NID_TIPO_PRODUCTO INT IDENTITY (1,1) NOT NULL,
	CTIPO_PRODUCTO VARCHAR (30) NOT NULL,
	BHABILITADO BIT NOT NULL,
	DFECHA_ALTA DATE NOT NULL,
	DFECHA_BAJA DATE NULL,
	CONSTRAINT PK_NID_TIPO_PRODUCTO PRIMARY KEY (NID_TIPO_PRODUCTO)
)
GO

CREATE TABLE DB_TIENDA.dbo.TBL_PRODUCTOS
(
	NID_PRODUCTO INT IDENTITY (1,1) NOT NULL,
	CPRODUCTO VARCHAR (30) NOT NULL,
	CPRECIO_COMPRA VARCHAR (6) NOT NULL,
	CPRECIO_VENTA VARCHAR (6) NOT NULL,
	NCANTIDAD INT NOT NULL,
	NID_MARCA INT NOT NULL,
	NID_TIPO_PRODUCTO INT NOT NULL,
	NID_PROVEEDOR INT NOT NULL,
	BHABILITADO BIT NOT NULL,
	DFECHA_ALTA DATE NOT NULL,
	DFECHA_BAJA DATE NULL,
	CONSTRAINT PK_NID_PRODUCTO PRIMARY KEY (NID_PRODUCTO),
	CONSTRAINT FK_NID_MARCA FOREIGN KEY (NID_MARCA) REFERENCES dbo.TBL_MARCAS (NID_MARCA),
	CONSTRAINT FK_NID_TIPO_PRODUCTO FOREIGN KEY (NID_TIPO_PRODUCTO) REFERENCES dbo.CAT_TIPO_PRODUCTOS (NID_TIPO_PRODUCTO),
	CONSTRAINT FK_NID_PROVEEDOR FOREIGN KEY (NID_PROVEEDOR) REFERENCES dbo.CAT_PROVEEDORES  (NID_PROVEEDOR)
)
GO

CREATE TABLE DB_TIENDA.dbo.CAT_PROVEEDORES
(
	NID_PROVEEDOR INT IDENTITY (1,1) NOT NULL,
	CNOMRES_PROVEEDOR VARCHAR (50) NOT NULL,
	CAPELLIDO_PATERNO VARCHAR(20) NOT NULL,
	CAPELLIDO_MATERNO VARCHAR(20) NULL,
	CTELEFONO CHAR (10) NULL, 
	BHABILITADO BIT NOT NULL,
	DFECHA_ALTA DATE NOT NULL,
	DFECHA_BAJA DATE NULL,
	CONSTRAINT PK_NID_PROVEEDOR PRIMARY KEY (NID_PROVEEDOR),
)
GO

CREATE TABLE DB_TIENDA.dbo.TBL_VENTAS
(
	NID_VENTA INT IDENTITY (1,1) NOT NULL,
	NID_PRODUCTO INT NOT NULL,
	NID_CLIENTE INT NULL,
	NCANTIDAD INT NOT NULL,
	BDEUDA BIT NULL,
	BHABILITADO BIT NOT NULL,
	DFECHA_ALTA DATE NOT NULL,
	DFECHA_BAJA DATE NULL,
	CONSTRAINT PK_NID_VENTA PRIMARY KEY (NID_VENTA),
	CONSTRAINT FK_NID_PRODUCTO2 FOREIGN KEY (NID_PRODUCTO) REFERENCES dbo.TBL_PRODUCTOS (NID_PRODUCTO),
	CONSTRAINT FK_NID_CLIENTE FOREIGN KEY (NID_CLIENTE) REFERENCES dbo.CAT_CLIENTES (NID_CLIENTE)
)
GO

CREATE TABLE DB_TIENDA.dbo.TBL_COMPRAS
(
	NID_COMPRA INT IDENTITY (1,1) NOT NULL,
	NID_PRODUCTO INT NOT NULL,
	NID_PROVEEDOR INT NULL,
	NCANTIDAD INT NOT NULL,
	BHABILITADO BIT NOT NULL,
	DFECHA_ALTA DATE NOT NULL,
	DFECHA_BAJA DATE NULL,
	CONSTRAINT PK_NID_COMPRA PRIMARY KEY (NID_COMPRA),
	CONSTRAINT FK_NID_PRODUCTO3 FOREIGN KEY (NID_PRODUCTO) REFERENCES dbo.TBL_PRODUCTOS (NID_PRODUCTO),
	CONSTRAINT FK_NID_CLIENTE2 FOREIGN KEY (NID_PROVEEDOR) REFERENCES dbo.CAT_PROVEEDORES (NID_PROVEEDOR)
)
GO