USE DB_TIENDA
GO


ALTER FUNCTION FN_GET_PRECIO
(
	@vnIDProducto INT
)
RETURNS FLOAT
	BEGIN
	RETURN CONVERT(FLOAT, (SELECT CPRECIO_VENTA FROM TBL_PRODUCTOS
	WHERE NID_PRODUCTO = @vnIDProducto))
	END
GO

DECLARE @RESULTADO FLOAT
SET @RESULTADO = dbo.FN_GET_PRECIO(1) 
SELECT @RESULTADO AS PRECIO
GO


CREATE FUNCTION FN_GET_PROVEEDOR
(
	@vnIDProducto INT
)
RETURNS INT
	BEGIN
		RETURN (SELECT NID_PROVEEDOR FROM TBL_PRODUCTOS
			    WHERE NID_PRODUCTO = @vnIDProducto)
	END
GO

DECLARE @RESULTADO INT
SET @RESULTADO = dbo.FN_GET_PROVEEDOR(7) 
SELECT @RESULTADO AS PROVEEDOR
GO


ALTER FUNCTION FN_NOMBRE_COMPLETO_CLIENTE
(
	@vnIDCliente INT
)
RETURNS VARCHAR(70)
	BEGIN
		DECLARE @NOMBRE VARCHAR(70)
		DECLARE @AM VARCHAR(20)
		SET @NOMBRE = (SELECT CNOMBRES FROM CAT_CLIENTES WHERE NID_CLIENTE = @vnIDCliente)
		SET @NOMBRE += ' ' + (SELECT CAPELLIDO_PATERNO FROM CAT_CLIENTES WHERE NID_CLIENTE = @vnIDCliente)
		SET @AM = (SELECT CAPELLIDO_MATERNO FROM CAT_CLIENTES WHERE NID_CLIENTE = @vnIDCliente)
		IF @AM IS NOT NULL
			BEGIN
				SET @NOMBRE += ' ' + @AM
			END
		RETURN @NOMBRE
	END
GO

DECLARE @RESULTADO VARCHAR(70)
SET @RESULTADO = dbo.FN_NOMBRE_COMPLETO_CLIENTE(1) 
SELECT @RESULTADO AS NOMBRE
GO

ALTER FUNCTION FN_NOMBRE_COMPLETO_PROVEEDOR
(
	@vnIDProveedor INT
)
RETURNS VARCHAR(70)
	BEGIN
		DECLARE @NOMBRE VARCHAR(70)
		DECLARE @AM VARCHAR(20)
		SET @NOMBRE = (SELECT CNOMRES_PROVEEDOR FROM CAT_PROVEEDORES WHERE NID_PROVEEDOR = @vnIDProveedor)
		SET @NOMBRE += ' ' + (SELECT CAPELLIDO_PATERNO FROM CAT_PROVEEDORES WHERE NID_PROVEEDOR = @vnIDProveedor)
		SET @AM = (SELECT CAPELLIDO_MATERNO FROM CAT_PROVEEDORES WHERE NID_PROVEEDOR = @vnIDProveedor)
		IF @AM IS NOT NULL
			BEGIN
				SET @NOMBRE += ' ' + @AM
			END
		RETURN @NOMBRE
	END
GO


DECLARE @RESULTADO VARCHAR(70)
SET @RESULTADO = dbo.FN_NOMBRE_COMPLETO_PROVEEDOR(1) 
SELECT @RESULTADO AS NOMBRE
GO

SELECT NID_CLIENTE FROM CAT_CLIENTES
WHERE lower(CNOMBRES) = 'cliente' and lower(CAPELLIDO_PATERNO) = 'prueba'
go


