USE DB_TIENDA
GO

INSERT INTO CAT_COMPAÑIAS ----------------------- Inserción de Nombres de Compañías
VALUES ('Coca-Cola Company', 1, GETDATE(), NULL)
INSERT INTO CAT_COMPAÑIAS
VALUES ('PepsiCo', 1, GETDATE(), NULL)
INSERT INTO CAT_COMPAÑIAS
VALUES ('Grupo Bimbo', 1, GETDATE(), NULL)
INSERT INTO CAT_COMPAÑIAS
VALUES ('Grupo Modelo', 1, GETDATE(), NULL)
INSERT INTO CAT_COMPAÑIAS
VALUES ('Grupo Lala', 1, GETDATE(), NULL)
INSERT INTO CAT_COMPAÑIAS
VALUES ('Alpura', 1, GETDATE(), NULL)
INSERT INTO CAT_COMPAÑIAS
VALUES ('Phillip Morris International', 1, GETDATE(), NULL)
INSERT INTO CAT_COMPAÑIAS
VALUES ('Nestlé', 1, GETDATE(), NULL)
INSERT INTO CAT_COMPAÑIAS
VALUES ('Jarritos', 1, GETDATE(), NULL)
INSERT INTO CAT_COMPAÑIAS
VALUES ('Gerber Products Company', 1, GETDATE(), NULL)
INSERT INTO CAT_COMPAÑIAS
VALUES ('Grupo Peñafiel', 1, GETDATE(), NULL)
INSERT INTO CAT_COMPAÑIAS
VALUES ('Red Cola', 1, GETDATE(), NULL)
INSERT INTO CAT_COMPAÑIAS
VALUES ('Danone', 1, GETDATE(), NULL)
INSERT INTO CAT_COMPAÑIAS
VALUES ('El Zorro', 1, GETDATE(), NULL)
SELECT * FROM CAT_COMPAÑIAS
GO

INSERT INTO CAT_TIPO_PRODUCTOS  ------- Inserción de presentaciones para líquidos
VALUES ('50ml.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('150ml.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('250ml.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('350ml.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('100ml.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('200ml.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('300ml.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('355ml.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('400ml.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('500ml.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('600ml.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('750ml.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('800ml.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('900ml.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('1L.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('1.1L.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('1.2L.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('1.5L.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('1.6L.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('1.8L.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('2L.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('2.5L.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('3L.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('3.5L.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('4L.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('5L.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('10L.', 1, GETDATE(), NULL)
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES ('20L.', 1, GETDATE(), NULL)


DECLARE @vnContador INT	------------------------ Inserción de presentaciones de forma iterativa para "sólidos"
DECLARE @vcCadena VARCHAR (10)
SET @vnContador = 1
WHILE (@vnContador <20)
	BEGIN
		SET @vcCadena = CONVERT(VARCHAR(3),@vnContador) + 'g.'		
		INSERT INTO CAT_TIPO_PRODUCTOS
		VALUES(@vcCadena, 1, GETDATE(), NULL)
		SET @vnContador += 1
	END	
SET @vnContador = 20
WHILE (@vnContador <100)
	BEGIN
		SET @vcCadena = CONVERT(VARCHAR(3),@vnContador) + 'g.'		
		INSERT INTO CAT_TIPO_PRODUCTOS
		VALUES(@vcCadena, 1, GETDATE(), NULL)
		SET @vnContador += 5
	END	
SET @vnContador = 100
WHILE (@vnContador < 500)
	BEGIN
		SET @vcCadena = CONVERT(VARCHAR(3),@vnContador) + 'g.'		
		INSERT INTO CAT_TIPO_PRODUCTOS
		VALUES(@vcCadena, 1, GETDATE(), NULL)
		SET @vnContador += 25
	END	
SET @vnContador = 500
WHILE (@vnContador < 1000)
	BEGIN
		SET @vcCadena = CONVERT(VARCHAR(3),@vnContador) + 'g.'		
		INSERT INTO CAT_TIPO_PRODUCTOS
		VALUES(@vcCadena, 1, GETDATE(), NULL)
		SET @vnContador += 50
	END	
INSERT INTO CAT_TIPO_PRODUCTOS
VALUES('1Kg', 1, GETDATE(), NULL)
SELECT * FROM CAT_TIPO_PRODUCTOS
GO

INSERT INTO TBL_MARCAS -------- Inserción de Marcas
VALUES('Coca-Cola', 1, 1, GETDATE(), NULL) ------------- Coca-Cola Company
INSERT INTO TBL_MARCAS 
VALUES('Fanta', 1, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Sprite', 1, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Coca-Cola Light', 1, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Coca-Cola Zero', 1, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Minute Maid', 1, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Powerade', 1, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Del Valle', 1, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Fuze Tea', 1, 1, GETDATE(), NULL)

INSERT INTO TBL_MARCAS 
VALUES('Pepsi', 2, 1, GETDATE(), NULL) ------------ PepsiCo
INSERT INTO TBL_MARCAS 
VALUES('Pepsi Light', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Pepsi Kick', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('7 Up', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('7 Up Libre', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Mirinda', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Manzanita Sol', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Gatorade', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Epura', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Lipton', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Sangría Casera', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Doritos', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Ruffles', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Fritos', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Cheetos', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Twistos', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Sunbites', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('KKwates', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Sabritas', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Rancheritos', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Tostitos', 2, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Sabritones', 2, 1, GETDATE(), NULL)

INSERT INTO TBL_MARCAS 
VALUES('Bimbo', 3, 1, GETDATE(), NULL) ------------ Grupo Bimbo
INSERT INTO TBL_MARCAS 
VALUES('Marinela', 3, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Barcel', 3, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Ricolino', 3, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Coronado', 3, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Tía Rosa', 3, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Lonchibón', 3, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Milpa Real', 3, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Saníssimo', 3, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Sunbeam', 3, 1, GETDATE(), NULL)

INSERT INTO TBL_MARCAS 
VALUES('Corona', 4, 1, GETDATE(), NULL) ------------ Grupo Modelo
INSERT INTO TBL_MARCAS 
VALUES('Barrilito', 4, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Estrella', 4, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('León', 4, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Modelo', 4, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Montejo', 4, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Pacífico', 4, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Victoria', 4, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Bocanegra', 4, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Tijuana', 4, 1, GETDATE(), NULL)

INSERT INTO TBL_MARCAS  ------------ Grupo Lala
VALUES('Lala', 5, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Yomi Lala', 5, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Nutri Leche', 5, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Nutri Deli', 5, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Soy Vita', 5, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS
VALUES('Queen', 5, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Leche Monarca', 5, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Chiquitin', 5, 1, GETDATE(), NULL)

INSERT INTO TBL_MARCAS 
VALUES('Alpura', 6, 1, GETDATE(), NULL) ------------ Alpura

INSERT INTO TBL_MARCAS 
VALUES('Malboro', 7, 1, GETDATE(), NULL) ------------ Phillip Morris International

INSERT INTO TBL_MARCAS 
VALUES('Nestlé Pureza Vital', 8, 1, GETDATE(), NULL) ------------ Nestlé
INSERT INTO TBL_MARCAS 
VALUES('Sta. María', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Perrier', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('La Lechera', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Carnation', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Nesquik', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Trix', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Lucky Charms', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Cookie Crisp', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Cheerios', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Corn Flakes', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Fitness', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Carlos V', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Abuelita', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Crunch', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('KitKat', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Freskas', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Larín', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Nescafé', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Nestea', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Coffee Mate', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Nido', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Gerber', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Helados Nestlé', 8, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Maggi', 8, 1, GETDATE(), NULL)

INSERT INTO TBL_MARCAS 
VALUES('Jarritos', 9, 1, GETDATE(), NULL) ------------ Jarritos

INSERT INTO TBL_MARCAS 
VALUES('Peñafiel', 11, 1, GETDATE(), NULL) ------------ Grupo Peñafiel
INSERT INTO TBL_MARCAS 
VALUES('Orange Crush', 11, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Aguafiel', 11, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Twist', 11, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Clamato', 11, 1, GETDATE(), NULL)

INSERT INTO TBL_MARCAS 
VALUES('Red Cola', 12, 1, GETDATE(), NULL) ------------ Red Cola

INSERT INTO TBL_MARCAS 
VALUES('Danone', 13, 1, GETDATE(), NULL) ------------ Danone
INSERT INTO TBL_MARCAS 
VALUES('Activia', 13, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Danonio', 13, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Bonafont', 13, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('Oikos', 13, 1, GETDATE(), NULL)
INSERT INTO TBL_MARCAS 
VALUES('VitaLinea', 13, 1, GETDATE(), NULL)

SELECT * FROM TBL_MARCAS
GO

INSERT INTO CAT_CLIENTES  ------------- Inserción de clientes de prueba
VALUES('Cliente', 'Prueba', '1', '5515746544', NULL, 1, GETDATE(),NULL)
INSERT INTO CAT_CLIENTES
VALUES('Cliente', 'Prueba', '2', '16680995', 'cliente_prueba2@gmail.com', 1, GETDATE(),NULL)

SELECT * FROM CAT_CLIENTES
WHERE BHABILITADO = 1
GO

INSERT INTO CAT_PROVEEDORES ------------Inserción de proveedores de prueba
VALUES('Proveedor', 'Prueba', NULL, '5548796453', 1, GETDATE(),NULL)
INSERT INTO CAT_PROVEEDORES
VALUES('Proveedor', 'Prueba', '2', '5545789865', 1, GETDATE(),NULL)

SELECT * FROM CAT_PROVEEDORES
WHERE BHABILITADO = 1
GO

INSERT INTO TBL_PRODUCTOS  --------------- Inserción productos
VALUES ('Coca-Cola', '18.00', '25.00', 20, 1 , 23 , 1, 1, GETDATE(), NULL)

INSERT INTO TBL_PRODUCTOS
VALUES ('Coca-Cola', '9.00', '12.00', 30, 1 , 11 , 1, 1, GETDATE(), NULL)

INSERT INTO TBL_PRODUCTOS
VALUES ('7 Up', '7.00', '11.00', 21, 13, 11 , 2, 1, GETDATE(), NULL)

INSERT INTO TBL_PRODUCTOS
VALUES ('Sabritas', '10.00', '13.00', 15, 28, 57 , 2, 1, GETDATE(), NULL)

SELECT * FROM TBL_PRODUCTOS
GO

delete from TBL_PRODUCTOS
where NID_PRODUCTO > 1