USE DB_TIENDA
GO


ALTER VIEW VDEUDORES
AS
	SELECT dbo.FN_NOMBRE_COMPLETO_CLIENTE(TV.NID_CLIENTE) AS CLIENTE, CTELEFONO, '$'+ CONVERT(VARCHAR,CONVERT(DECIMAL(10,2), SUM(CONVERT(FLOAT, CPRECIO_VENTA)))) AS [Total a pagar] FROM TBL_VENTAS AS TV
	INNER JOIN CAT_CLIENTES AS CC
	ON CC.NID_CLIENTE = TV.NID_CLIENTE
	INNER JOIN TBL_PRODUCTOS AS TP 
	ON TV.NID_PRODUCTO = TP.NID_PRODUCTO
	WHERE BDEUDA =1
	GROUP BY TV.NID_CLIENTE, CTELEFONO
GO

SELECT * FROM VDEUDORES
GO


ALTER VIEW VCOMPRAS
AS
	SELECT CPRODUCTO AS PRODUCTO,
		   DBO.FN_NOMBRE_COMPLETO_PROVEEDOR(TC.NID_PROVEEDOR) AS [NOMBRE PORVEEDOR],
		   TC.NCANTIDAD AS CANTIDAD,
		   '$' + CONVERT(VARCHAR, CONVERT(DECIMAL(10,2), (TC.NCANTIDAD * CONVERT(FLOAT, CPRECIO_COMPRA)))) AS TOTAL,
		   TC.DFECHA_ALTA AS FECHA 
	FROM CAT_PROVEEDORES AS CT
	INNER JOIN TBL_COMPRAS AS TC
	ON TC.NID_PROVEEDOR = CT.NID_PROVEEDOR
	INNER JOIN TBL_PRODUCTOS AS TP
	ON TC.NID_PRODUCTO = TP.NID_PRODUCTO
GO

SELECT * FROM VCOMPRAS
ORDER BY FECHA ASC
GO


CREATE VIEW VVENTAS
AS
	SELECT CPRODUCTO AS PRODUCTO,
		   DBO.FN_NOMBRE_COMPLETO_CLIENTE(TV.NID_CLIENTE) AS [NOMBRE CLIENTE],
		   TV.NCANTIDAD AS CANTIDAD,
		   '$' + CONVERT(VARCHAR, CONVERT(DECIMAL(10,2), (TV.NCANTIDAD * CONVERT(FLOAT, CPRECIO_VENTA)))) AS TOTAL,
		   TV.DFECHA_ALTA AS FECHA 
	FROM CAT_CLIENTES AS CC
	RIGHT JOIN TBL_VENTAS AS TV
	ON TV.NID_CLIENTE = CC.NID_CLIENTE
	INNER JOIN TBL_PRODUCTOS AS TP
	ON TV.NID_PRODUCTO = TP.NID_PRODUCTO
GO

SELECT * FROM VVENTAS
GO


SELECT DATENAME(MONTH, VV.FECHA) AS MES, 
'$' + CONVERT(VARCHAR, CONVERT(DECIMAL(10,2), SUM(CONVERT(FLOAT, SUBSTRING(VV.TOTAL, 2, LEN(VV.TOTAL)))))) AS VENTAS
FROM VVENTAS AS VV
GROUP BY DATENAME(MONTH, VV.FECHA)
ORDER BY DATENAME(MONTH, VV.FECHA)

SELECT DATENAME(MONTH, FECHA) FROM VVENTAS

SELECT * FROM VVENTAS

SELECT CONVERT(FLOAT, SUBSTRING(TOTAL, 2, LEN(TOTAL))) FROM VVENTAS